/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsUseThemeRouteImport } from './routes/docs.use-theme'
import { Route as DocsTypographyRouteImport } from './routes/docs.typography'
import { Route as DocsTypescriptRouteImport } from './routes/docs.typescript'
import { Route as DocsTypesRouteImport } from './routes/docs.types'
import { Route as DocsThemeProviderRouteImport } from './routes/docs.theme-provider'
import { Route as DocsSpacingRouteImport } from './routes/docs.spacing'
import { Route as DocsShadowsRouteImport } from './routes/docs.shadows'
import { Route as DocsRadiusRouteImport } from './routes/docs.radius'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsCustomizationRouteImport } from './routes/docs.customization'
import { Route as DocsCssVariablesRouteImport } from './routes/docs.css-variables'
import { Route as DocsColorsRouteImport } from './routes/docs.colors'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUseThemeRoute = DocsUseThemeRouteImport.update({
  id: '/use-theme',
  path: '/use-theme',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTypographyRoute = DocsTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTypescriptRoute = DocsTypescriptRouteImport.update({
  id: '/typescript',
  path: '/typescript',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTypesRoute = DocsTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => DocsRoute,
} as any)
const DocsThemeProviderRoute = DocsThemeProviderRouteImport.update({
  id: '/theme-provider',
  path: '/theme-provider',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSpacingRoute = DocsSpacingRouteImport.update({
  id: '/spacing',
  path: '/spacing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsShadowsRoute = DocsShadowsRouteImport.update({
  id: '/shadows',
  path: '/shadows',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRadiusRoute = DocsRadiusRouteImport.update({
  id: '/radius',
  path: '/radius',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCustomizationRoute = DocsCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCssVariablesRoute = DocsCssVariablesRouteImport.update({
  id: '/css-variables',
  path: '/css-variables',
  getParentRoute: () => DocsRoute,
} as any)
const DocsColorsRoute = DocsColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/colors': typeof DocsColorsRoute
  '/docs/css-variables': typeof DocsCssVariablesRoute
  '/docs/customization': typeof DocsCustomizationRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/radius': typeof DocsRadiusRoute
  '/docs/shadows': typeof DocsShadowsRoute
  '/docs/spacing': typeof DocsSpacingRoute
  '/docs/theme-provider': typeof DocsThemeProviderRoute
  '/docs/types': typeof DocsTypesRoute
  '/docs/typescript': typeof DocsTypescriptRoute
  '/docs/typography': typeof DocsTypographyRoute
  '/docs/use-theme': typeof DocsUseThemeRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/colors': typeof DocsColorsRoute
  '/docs/css-variables': typeof DocsCssVariablesRoute
  '/docs/customization': typeof DocsCustomizationRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/radius': typeof DocsRadiusRoute
  '/docs/shadows': typeof DocsShadowsRoute
  '/docs/spacing': typeof DocsSpacingRoute
  '/docs/theme-provider': typeof DocsThemeProviderRoute
  '/docs/types': typeof DocsTypesRoute
  '/docs/typescript': typeof DocsTypescriptRoute
  '/docs/typography': typeof DocsTypographyRoute
  '/docs/use-theme': typeof DocsUseThemeRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/colors': typeof DocsColorsRoute
  '/docs/css-variables': typeof DocsCssVariablesRoute
  '/docs/customization': typeof DocsCustomizationRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/radius': typeof DocsRadiusRoute
  '/docs/shadows': typeof DocsShadowsRoute
  '/docs/spacing': typeof DocsSpacingRoute
  '/docs/theme-provider': typeof DocsThemeProviderRoute
  '/docs/types': typeof DocsTypesRoute
  '/docs/typescript': typeof DocsTypescriptRoute
  '/docs/typography': typeof DocsTypographyRoute
  '/docs/use-theme': typeof DocsUseThemeRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/colors'
    | '/docs/css-variables'
    | '/docs/customization'
    | '/docs/examples'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/radius'
    | '/docs/shadows'
    | '/docs/spacing'
    | '/docs/theme-provider'
    | '/docs/types'
    | '/docs/typescript'
    | '/docs/typography'
    | '/docs/use-theme'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/colors'
    | '/docs/css-variables'
    | '/docs/customization'
    | '/docs/examples'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/radius'
    | '/docs/shadows'
    | '/docs/spacing'
    | '/docs/theme-provider'
    | '/docs/types'
    | '/docs/typescript'
    | '/docs/typography'
    | '/docs/use-theme'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/colors'
    | '/docs/css-variables'
    | '/docs/customization'
    | '/docs/examples'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/radius'
    | '/docs/shadows'
    | '/docs/spacing'
    | '/docs/theme-provider'
    | '/docs/types'
    | '/docs/typescript'
    | '/docs/typography'
    | '/docs/use-theme'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/use-theme': {
      id: '/docs/use-theme'
      path: '/use-theme'
      fullPath: '/docs/use-theme'
      preLoaderRoute: typeof DocsUseThemeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/typography': {
      id: '/docs/typography'
      path: '/typography'
      fullPath: '/docs/typography'
      preLoaderRoute: typeof DocsTypographyRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/typescript': {
      id: '/docs/typescript'
      path: '/typescript'
      fullPath: '/docs/typescript'
      preLoaderRoute: typeof DocsTypescriptRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/types': {
      id: '/docs/types'
      path: '/types'
      fullPath: '/docs/types'
      preLoaderRoute: typeof DocsTypesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/theme-provider': {
      id: '/docs/theme-provider'
      path: '/theme-provider'
      fullPath: '/docs/theme-provider'
      preLoaderRoute: typeof DocsThemeProviderRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/spacing': {
      id: '/docs/spacing'
      path: '/spacing'
      fullPath: '/docs/spacing'
      preLoaderRoute: typeof DocsSpacingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/shadows': {
      id: '/docs/shadows'
      path: '/shadows'
      fullPath: '/docs/shadows'
      preLoaderRoute: typeof DocsShadowsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/radius': {
      id: '/docs/radius'
      path: '/radius'
      fullPath: '/docs/radius'
      preLoaderRoute: typeof DocsRadiusRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/customization': {
      id: '/docs/customization'
      path: '/customization'
      fullPath: '/docs/customization'
      preLoaderRoute: typeof DocsCustomizationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/css-variables': {
      id: '/docs/css-variables'
      path: '/css-variables'
      fullPath: '/docs/css-variables'
      preLoaderRoute: typeof DocsCssVariablesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/colors': {
      id: '/docs/colors'
      path: '/colors'
      fullPath: '/docs/colors'
      preLoaderRoute: typeof DocsColorsRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsColorsRoute: typeof DocsColorsRoute
  DocsCssVariablesRoute: typeof DocsCssVariablesRoute
  DocsCustomizationRoute: typeof DocsCustomizationRoute
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsRadiusRoute: typeof DocsRadiusRoute
  DocsShadowsRoute: typeof DocsShadowsRoute
  DocsSpacingRoute: typeof DocsSpacingRoute
  DocsThemeProviderRoute: typeof DocsThemeProviderRoute
  DocsTypesRoute: typeof DocsTypesRoute
  DocsTypescriptRoute: typeof DocsTypescriptRoute
  DocsTypographyRoute: typeof DocsTypographyRoute
  DocsUseThemeRoute: typeof DocsUseThemeRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsColorsRoute: DocsColorsRoute,
  DocsCssVariablesRoute: DocsCssVariablesRoute,
  DocsCustomizationRoute: DocsCustomizationRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsRadiusRoute: DocsRadiusRoute,
  DocsShadowsRoute: DocsShadowsRoute,
  DocsSpacingRoute: DocsSpacingRoute,
  DocsThemeProviderRoute: DocsThemeProviderRoute,
  DocsTypesRoute: DocsTypesRoute,
  DocsTypescriptRoute: DocsTypescriptRoute,
  DocsTypographyRoute: DocsTypographyRoute,
  DocsUseThemeRoute: DocsUseThemeRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
